# Generated by Django 2.1.4 on 2018-12-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181221_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('ficha_medica', models.FileField(upload_to='')),
                ('autorizacao', models.FileField(upload_to='')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together={('nome', 'idade', 'email', 'grupo')},
        ),
    ]
