# Generated by Django 2.1.4 on 2019-02-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181221_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='')),
            ],
        ),
    ]
