# Generated by Django 2.1.4 on 2019-02-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_boletim'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletim',
            name='resumo',
            field=models.TextField(default='resumo'),
        ),
    ]
