# Generated by Django 2.1.4 on 2019-02-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_boletim_resumo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boletim',
        ),
    ]
