# Generated by Django 2.1.4 on 2019-02-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_boletim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='')),
                ('capa', models.FileField(upload_to='')),
                ('resumo', models.TextField(default='resumo')),
            ],
        ),
    ]
