# Generated by Django 2.1.4 on 2019-02-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_boletim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boletim',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='participante',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
    ]
